imports:
    - php

build:
    nodes:
        php:
            environment:
                php: '7.0'

        php71:
            environment:
                php: '7.1'
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                        coverage:
                            file: 'coverage.xml'
                            format: 'clover'

filter:
    excluded_paths:
        - docs/
        - tests/

tools:
    php_mess_detector: true
    php_cpd:
        excluded_dirs:
            - docs/
            - tests/
    php_loc:
        excluded_dirs:
            - docs/
            - tests/
    php_pdepend:
        excluded_dirs:
            1: docs/
            2: tests/
